version: "3.7"

networks:
  proxy:
    name: 'proxy-network'
    external: true

services:
  caddy:
    container_name: 'site-appa8'
    build: .
    pull_policy: build
    restart: unless-stopped

    labels:
      - traefik.enable=true
      # Router configuration
      ## Rule based on the Host of the request
      - traefik.http.routers.folhetos_route.rule=Host(`appa8.com`) || Host(`www.appa8.com`)
      # Service configuration
      ## 80 is the port that the whoami container is listening to
      - traefik.http.services.folhetos_route.loadbalancer.server.port=80
      - traefik.http.routers.folhetos_route.tls=true
      - traefik.http.routers.folhetos_route.tls.certresolver=leresolver

    networks:
      - proxy
